title: WCA Web Development Documentation
description: A collection of documentation and guides for development of the WCA's web ecosystem.
theme: just-the-docs

url: https://thewca.github.io

aux_links:
  WCA Main Repo: https://github.com/thewca/worldcubeassociation.org
