title: WCA Web Dev
description: A collection of documentation and guides for development of the WCA's web ecosystem.
theme: just-the-docs

url: https://thewca.github.io
favicon_ico: /assets/images/favicon.ico
color_scheme: dark

aux_links:
  WCA Main Repo: https://github.com/thewca/worldcubeassociation.org

nav_external_links:
  - title: API 
    url: https://wca-rest-api.robiningelbrecht.be/
